### PR TITLE
Update redux deps

### PR DESCRIPTION
**Pull request by cpak**
redux -> 4.0.5
redux-devtools-extension -> 2.13.8

We should enable dependabot or similar on the ramverk1 repos. Mostly making this PR to silence alerts in code scanning tools...

### CODE REVIEW

**Comment by frippz** [comment]
redux is a major version upgrade. Do we need to test this in `search-frontend` first, @martaan?

**Comment by martaan** [comment]
> redux is a major version upgrade. Do we need to test this in `search-frontend` first, @martaan?

Yes I trying it out now.  Replace `search-frontend` package.json line 67 with `"ramverk1-redux-devtools": "git+https://github.com/mammutmw/ramverk1-redux-devtools.git#upgrade-redux-deps"` and do a npm install to try it out as well.

**Comment by martaan** [comment]
To me it seems like it works fine. Could you verify @frippz

**Review by frippz — APPROVED** [review]
@martaan Yep, it seems to work fine!

**Pull request merged**
